name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve?
      placeholder: Describe the user pain or business need.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What do you want to happen?
      placeholder: Outline the feature or change.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope / Notes
      description: Include constraints, dependencies, or edge cases.
      placeholder: Additional details.
    validations:
      required: false
