spring.application.name=web-backend

# APick API 설정
apick.api.key=${APICK_API_KEY:289918cfd374753a98566d5e9e6d3f56}
apick.api.url=${APICK_API_URL:https://apick.app/rest/check_spam_number}

# Gemini API 설정
gemini.api.key=${GEMINI_API_KEY:AIzaSyAuSSJdu5eUeLB2gky0XHV-Ar45IwlfA4U}
